# Generated by Django 2.1.5 on 2019-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakageafter',
            fields=[
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('opertionTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('afterID', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='报废单ID')),
                ('reason', models.CharField(max_length=300, verbose_name='报废原因')),
                ('drugID', models.CharField(max_length=100, verbose_name='药品ID')),
                ('afterbrugname', models.CharField(max_length=100, verbose_name='报废药品名称')),
                ('damagednum', models.IntegerField(default=0, verbose_name='报废量')),
                ('damagetime', models.DateTimeField(auto_now=True, verbose_name='报废时间')),
                ('hwh', models.CharField(max_length=50, verbose_name='货位号')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
