# Generated by Django 2.1.5 on 2019-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakagebefore',
            fields=[
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('opertionTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('beforeID', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='报损单ID')),
                ('beforebrugname', models.CharField(max_length=100, verbose_name='报损药品名称')),
                ('damagednum', models.IntegerField(default=0, verbose_name='损坏量')),
                ('damagetime', models.DateTimeField(auto_now=True, verbose_name='报损时间')),
                ('supplierID', models.CharField(max_length=100, verbose_name='供应商ID')),
                ('pactID', models.CharField(max_length=100, verbose_name='合同ID')),
                ('drugID', models.CharField(max_length=100, verbose_name='药品ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
